An equals check was added in 2.08 of 21 December 2015 (commit eed8d9c63c030810b9c44de9558fcb85cda1c6c6). It has the (unintended) side-effect that it prevents users from "mixing types" in the behavior part of the spec (this is rare) when checking liveness properties:
```tla

  ...

  Next ==
    \/ x' \in 1..100
    \/ x' = TRUE
    \/ x' = "abc"

  Prop ==
    <>[]TRUE \* Actual property doesn't matter.
```

Instead, it can causes a hard-to-debug exception (iff there are enough
successor states to cause collisions above):

  Error: TLC threw an unexpected exception.
  This was probably caused by an error in the spec or model.
  See the User Output or TLC Console for clues to what happened.
  The exception was a java.lang.RuntimeException
  : Attempted to check equality of string "" with non-string:
  FALSE

[Bug][TLC][Regression]