Change to instance type with higher storage capacity when running performance benchmarks
`/usr/bin/ant: 1: exec: /home/runner/_work/_tool/Java_Zulu_jdk/11.0.25-9/x64/bin/java: Exec format error
Error: Process completed with exit code 126.`

https://github.com/actions/setup-java?tab=readme-ov-file#usage

[Build]