java.lang.ArrayIndexOutOfBoundsException with `TLCExt!lassoOrdinal` when printing liveness violations in simulation mode.
```
"CounterExample written:
states/tlc2.tool.liveness.simulation.Example1Test.json"
Error: Evaluating assumption line 13, col 5 to line 14, col 69 of module
_TLCTrace failed.
Attempted to apply the operator overridden by the Java method
public static tlc2.value.impl.Value
tlc2.module.TLCExt.lassoOrdinal(tlc2.value.impl.Value),
but it produced the following error:
Index 10 out of bounds for length 10
```

A regression was introduced in commit
`1156d779b7de3b04841112f75c0c8ddf39f1789b`, which caused all but one
instance of the same state in the trace to be removed. The removal was a
side effect of storing states in a Map indexed by state fingerprints.

[Bug][TLC]

Signed-off-by: Markus Alexander Kuppe <github.com@lemmster.de>