Consistently pin all maven antrun plugins to version 1.8.
This commit fixes the following build error of our Github action:

```
Error:  Failed to execute goal
org.apache.maven.plugins:maven-antrun-plugin:3.1.0:run (default) on
project org.lamport.tla.toolbox.test: You are using 'tasks' which has
been removed from the maven-antrun-plugin. Please use 'target' and refer
to the >>Major Version Upgrade to version 3.0.0<< on the plugin site.
```

[Bug][Build]