Remove `Trace` operator from ALIAS test.
The previous commit introduced support for reporting ALIAS evaluation
errors. This change exposed an issue where the `Trace` operator fails to
evaluate for the last (fourth) state of the counterexample.

```
java.lang.ArrayIndexOutOfBoundsException: Index 32767 out of bounds for
length 1
	at tlc2.tool.ConcurrentTLCTrace$Record.getRecord(ConcurrentTLCTrace.java:307)
	at tlc2.tool.ConcurrentTLCTrace.getTrace(ConcurrentTLCTrace.java:93)
	at tlc2.tool.ModelChecker.getTraceInfo(ModelChecker.java:1078)
	at tlc2.module.TLCExt.getTrace(TLCExt.java:272)
	at tlc2.value.impl.EvaluatingValue.eval(EvaluatingValue.java:86)
	at tlc2.tool.impl.Tool.evalApplImpl(Tool.java:1967)
	at tlc2.tool.impl.FastTool.evalAppl(FastTool.java:117)
	at tlc2.tool.impl.Tool.evalImpl(Tool.java:1732)
	at tlc2.tool.impl.FastTool.eval(FastTool.java:110)
	at tlc2.tool.impl.Tool.evalApplImpl(Tool.java:2325)
	at tlc2.tool.impl.FastTool.evalAppl(FastTool.java:117)
	at tlc2.tool.impl.Tool.evalImpl(Tool.java:1732)
	at tlc2.tool.impl.FastTool.eval(FastTool.java:110)
	at tlc2.tool.impl.Tool.evalApplImpl(Tool.java:2314)
	at tlc2.tool.impl.FastTool.evalAppl(FastTool.java:117)
	at tlc2.tool.impl.Tool.evalImpl(Tool.java:1732)
	at tlc2.tool.impl.FastTool.eval(FastTool.java:110)
	at tlc2.tool.impl.Tool.eval(Tool.java:1700)
	at tlc2.tool.impl.Tool.evalAlias(Tool.java:1661)
	at tlc2.tool.impl.Tool.evalAlias(Tool.java:1630)
	at tlc2.tool.Worker.doPostCondition(Worker.java:670)
	at tlc2.tool.Worker.doNextSetErr(Worker.java:617)
	at tlc2.tool.Worker.doNextCheckInvariants(Worker.java:566)
	at tlc2.tool.Worker.addElement(Worker.java:460)
	at tlc2.tool.impl.Tool.getNextStates0(Tool.java:969)
	at tlc2.tool.impl.Tool.getNextStates(Tool.java:957)
	at tlc2.tool.impl.Tool.getNextStatesApplSwitch(Tool.java:1334)
	at tlc2.tool.impl.Tool.getNextStatesApplImpl(Tool.java:1121)
	at tlc2.tool.impl.FastTool.getNextStatesAppl(FastTool.java:96)
	at tlc2.tool.impl.Tool.getNextStatesImpl(Tool.java:900)
	at tlc2.tool.impl.FastTool.getNextStates(FastTool.java:89)
	at tlc2.tool.impl.Tool.getNextStates0(Tool.java:990)
	at tlc2.tool.impl.Tool.getNextStates(Tool.java:957)
	at tlc2.tool.impl.Tool.getNextStatesApplUsrDefOp(Tool.java:1142)
	at tlc2.tool.impl.Tool.getNextStatesApplImpl(Tool.java:1117)
	at tlc2.tool.impl.FastTool.getNextStatesAppl(FastTool.java:96)
	at tlc2.tool.impl.Tool.getNextStatesImpl(Tool.java:900)
	at tlc2.tool.impl.FastTool.getNextStates(FastTool.java:89)
	at tlc2.tool.impl.Tool.getNextStates0(Tool.java:990)
	at tlc2.tool.impl.Tool.getNextStates(Tool.java:957)
	at tlc2.tool.impl.Tool.getNextStatesApplSwitch(Tool.java:1334)
	at tlc2.tool.impl.Tool.getNextStatesApplImpl(Tool.java:1121)
	at tlc2.tool.impl.FastTool.getNextStatesAppl(FastTool.java:96)
	at tlc2.tool.impl.Tool.getNextStatesImpl(Tool.java:900)
	at tlc2.tool.impl.FastTool.getNextStates(FastTool.java:89)
	at tlc2.tool.impl.Tool.getNextStatesApplSwitch(Tool.java:1161)
	at tlc2.tool.impl.Tool.getNextStatesApplImpl(Tool.java:1121)
	at tlc2.tool.impl.FastTool.getNextStatesAppl(FastTool.java:96)
	at tlc2.tool.impl.Tool.getNextStatesImpl(Tool.java:900)
	at tlc2.tool.impl.FastTool.getNextStates(FastTool.java:89)
	at tlc2.tool.impl.Tool.getNextStates(Tool.java:885)
	at tlc2.tool.impl.Tool.getNextStates(Tool.java:879)
	at tlc2.tool.Worker.run(Worker.java:116)
```

Background: The value `32767` is the default `TLCState#workerId`
assigned before a `TLCState` is serialized to disk.

Until the underlying evaluation issue is fixed, the `Trace` operator is
temporarily removed from this test.  This commit should eventually be
reverted.

Revealed by Github issue #543
https://github.com/tlaplus/tlaplus/issues/543

[Tests][TLC]

Signed-off-by: Markus Alexander Kuppe <github.com@lemmster.de>