New Java 11 dependency, Java 8 causes "NoSuchMethodError: String.strip()".
It is low risk to rely on string trimming for command-line input that is
not unicode-aware. TLC will report an error.

Addresses Github issue #462
https://github.com/tlaplus/tlaplus/issues/462

[Refactor][TLC]